"""Fork-only verification of nasa/trick#2216, generated by ChatGPT.

Imports the complete upstream TrickWorkflow module and uses real temporary files.
No simulation build, target-hardware test, or full TrickOps suite is performed.
"""

import difflib
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[2]
SOURCE = Path('share/trick/trickops/TrickWorkflow.py')
BASE = '8b25adf131b4886dfc11f1229c1acce621646326'


class ComparisonRetryTests(unittest.TestCase):
    """Exercise independent retry transitions without starting a simulation."""

    def setUp(self):
        from TrickWorkflow import TrickWorkflow
        from WorkflowCommon import Job

        directory = tempfile.TemporaryDirectory()
        self.addCleanup(directory.cleanup)
        self.test_file = Path(directory.name) / 'test.dat'
        self.baseline_file = Path(directory.name) / 'baseline.dat'
        self.comparison = TrickWorkflow.Comparison(
            str(self.test_file), str(self.baseline_file)
        )
        self.status = Job.Status

    def test_missing_files_recover_when_both_arrive(self):
        self.assertEqual(self.comparison.compare(), self.status.FAILED)
        self.assertEqual(self.comparison.missing,
                         [str(self.test_file), str(self.baseline_file)])
        self.test_file.write_bytes(b'same\n')
        self.baseline_file.write_bytes(b'same\n')
        self.assertEqual(self.comparison.compare(), self.status.SUCCESS)
        self.assertEqual(self.comparison.missing, [])

    def test_retries_report_only_files_still_missing(self):
        for _ in range(2):
            self.assertEqual(self.comparison.compare(), self.status.FAILED)
            self.assertEqual(self.comparison.missing,
                             [str(self.test_file), str(self.baseline_file)])
        self.test_file.write_bytes(b'same\n')
        self.assertEqual(self.comparison.compare(), self.status.FAILED)
        self.assertEqual(self.comparison.missing, [str(self.baseline_file)])

    def test_success_then_missing_then_mismatch_then_recovery(self):
        self.test_file.write_bytes(b'same\n')
        self.baseline_file.write_bytes(b'same\n')
        self.assertEqual(self.comparison.compare(), self.status.SUCCESS)
        self.test_file.unlink()
        self.assertEqual(self.comparison.compare(), self.status.FAILED)
        self.assertEqual(self.comparison.missing, [str(self.test_file)])
        self.test_file.write_bytes(b'different\n')
        self.assertEqual(self.comparison.compare(), self.status.FAILED)
        self.assertEqual(self.comparison.missing, [])
        self.test_file.write_bytes(b'same\n')
        self.assertEqual(self.comparison.compare(), self.status.SUCCESS)
        self.assertEqual(self.comparison.missing, [])


def run_tests():
    sys.path.insert(0, str(ROOT / 'share/trick/trickops'))
    suite = unittest.defaultTestLoader.loadTestsFromTestCase(ComparisonRetryTests)
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    print('PROBE_RESULT ' + json.dumps({
        'tests': result.testsRun,
        'failures': len(result.failures),
        'errors': len(result.errors),
        'skipped': len(result.skipped),
    }), flush=True)
    return 0 if result.wasSuccessful() else 1


def run_probe():
    source = ROOT / SOURCE
    original = source.read_bytes()
    expected = subprocess.run(
        ['git', 'show', f'{BASE}:{SOURCE.as_posix()}'], cwd=ROOT,
        check=True, capture_output=True,
    ).stdout
    if original != expected:
        raise RuntimeError('Source differs from the pinned upstream baseline')
    needle = '            for hs in [self.test_data, self.baseline_data]:\n'
    text = original.decode('utf-8')
    if text.count(needle) != 1:
        raise RuntimeError('Expected exactly one comparison-loop anchor')
    candidate = text.replace(needle, '            self.missing = []\n' + needle)
    reports = ROOT / 'probe-results'
    reports.mkdir(exist_ok=True)
    patch = ''.join(difflib.unified_diff(
        text.splitlines(keepends=True), candidate.splitlines(keepends=True),
        fromfile='a/' + SOURCE.as_posix(), tofile='b/' + SOURCE.as_posix(),
    ))
    (reports / 'fix-comparison-retry.patch').write_text(patch, encoding='utf-8')

    def check(label, failures, exit_code):
        completed = subprocess.run(
            [sys.executable, str(Path(__file__).resolve()), '--tests'],
            cwd=ROOT, capture_output=True, text=True, timeout=60,
        )
        output = completed.stdout + completed.stderr
        (reports / f'{label}.log').write_text(output, encoding='utf-8')
        print(f'=== {label} ===\n{output}', flush=True)
        markers = [line.removeprefix('PROBE_RESULT ')
                   for line in completed.stdout.splitlines()
                   if line.startswith('PROBE_RESULT ')]
        if len(markers) != 1:
            raise RuntimeError(f'{label}: missing or ambiguous test summary')
        summary = json.loads(markers[0])
        required = {'tests': 3, 'failures': failures, 'errors': 0, 'skipped': 0}
        if completed.returncode != exit_code or summary != required:
            raise RuntimeError(f'{label}: unexpected outcome {summary}')
        return summary

    before = check('upstream', 3, 1)
    try:
        source.write_text(candidate, encoding='utf-8')
        after = check('candidate', 0, 0)
    finally:
        source.write_bytes(original)

    subprocess.run(
        ['git', 'apply', '--check', str(reports / 'fix-comparison-retry.patch')],
        cwd=ROOT, check=True,
    )
    (reports / 'results.json').write_text(json.dumps({
        'baseline_commit': BASE,
        'source_sha256': hashlib.sha256(original).hexdigest(),
        'python': sys.version,
        'upstream': before,
        'candidate': after,
        'patch_application_check': 'passed',
        'scope': 'Complete module imports; three real-filesystem regression tests',
        'not_tested': ['full TrickOps suite', 'simulation build', 'target hardware'],
        'ai_disclosure': 'ChatGPT generated the probe and candidate patch.',
    }, indent=2) + '\n', encoding='utf-8')
    print('Verified expected baseline failures and candidate passes.', flush=True)
    return 0


if __name__ == '__main__':
    raise SystemExit(run_tests() if sys.argv[1:] == ['--tests'] else run_probe())
